### ISSUE TITLE
for each...in statement is deprecated

### ISSUE THREAD

**Issue by asamuzaK** [piroor/openlinkintab#17]
`SyntaxError: missing ( after for  prefs.js:154:8`
in browser console.

```
		addPrefListener : function(aObserver) 
		{
			var domains = ('domains' in aObserver) ? aObserver.domains : [aObserver.domain] ;
			try {
				for each (var domain in domains)
					this.Prefs.addObserver(domain, aObserver, false);
			}
			catch(e) {
			}
		},
```

`for each...in` statement is deprecated.
Use `for of` instead.
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for_each...in

**Comment by piroor** [comment]
It is already fixed on master but not released yet...

**Comment by asamuzaK** [comment]
Got it.
