### ISSUE TITLE
Open a link in the _current_ tab.

### ISSUE THREAD

**Issue by trismarck** [piroor/openlinkintab#7]
After installing the extension, it seems that there is no easy way to open the link in the _current_ tab. Could Ctrl+Shift+click (which normally opens the link in the new tab and navigates to the link) be remapped or some other solution provided so that there is a way to open the link in the current tab?
As a workaround, to open the link in the current tab, one can right click on the link: Copy Link Location: focus location bar: paste: Enter ; but it is cumbersome.

**Comment by piroor** [comment]
Hmm, the preference seems not working on the version 1.0.2016011401. It is a regression...

**Comment by piroor** [comment]
Version 1.0.x and later the secret preference cannot be supported, anymore by technical reason.

**Comment by piroor** [comment]
Instead, I recommend you to use the addon "Open Link in Current".
https://addons.mozilla.org/firefox/addon/open-link-in-current/

**Comment by trismarck** [comment]
Ok. Thank you.
